### ISSUE TITLE
ProbeBasic: ToolTable crashes when loading

### ISSUE THREAD

**Issue by KurtJacobson** [kcjengr/qtpyvcp#1]
Reported by boban_serb on matrix: [linuxcnc.report.txt](https://github.com/kcjengr/qtpyvcp/files/2746568/linuxcnc.report.txt)

It seems ProbeBasic crashes when clicking on the Tool tab.

I can't reproduce this on my my machine, so it may have something to do with the data in the tool table file.

**Traceback:**
```
Traceback (most recent call last):
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/widgets/input_widgets/tool_table.py", line 190, in data
    return self._data(self.tool_list[index.row()], index.column(), role)
  File "/home/cnc/.local/lib/python2.7/site-packages/qtpyvcp/widgets/input_widgets/tool_table.py", line 213, in _data
    return item[3]
IndexError: list index out of range
```

**Comment by bobanSerb** [comment]
I found why, if the tool.tbl file is empty, it causes the program crash

**Comment by TurBoss** [comment]
I'll take a look

**Comment by TurBoss** [comment]
I can't reproduce this issue

**Comment by KurtJacobson** [comment]
@bobanSerb I can reproduce that now, thank you!
So it looks the error is caused if the D and offset values are missing.

**Comment by KurtJacobson** [comment]
@bobanSerb I just pushed what I think is a fix. Can you test it?
Thanks!

**Comment by bobanSerb** [comment]
It's ok now , thanks.
