### ISSUE TITLE
Report of Axis Zeroing button not working

### ISSUE THREAD

**Issue by andypugh** [kcjengr/qtpyvcp#122]
https://github.com/LinuxCNC/linuxcnc/issues/2587#issuecomment-1637300463

Despite what is said there, I am not sure that there is enough code commonality for the QTVCP widget update to fix this similar issue in Probe-Basic / qtpvcp. 

This is just a heads-up rather than a bug report, I have not attempted to reproduce the reported issue.

**Comment by TurBoss** [comment]
no issues found

Thanks!
