### ISSUE TITLE
AttributeError: module 'monokrom' has no attribute 'VCP_CONFIG_FILE'

### ISSUE THREAD

**Issue by kang2k10** [kcjengr/qtpyvcp#130]
Linuxcnc 2.9 from official iso
install qtpyvcp from script "/usr/lib/python3/dist-packages/qtvcp/designer/install_script"
from this repo, clone example.
after run sim.qtpyvcp/xyz.ini
this error:
  File "/usr/lib/python3/dist-packages/qtpyvcp/vcp_chooser/vcp_chooser.py", line 79, in get_vcp_data
    vcp_config_file = vcp.VCP_CONFIG_FILE
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'monokrom' has no attribute 'VCP_CONFIG_FILE'

**Comment by KurtJacobson** [comment]
I have this same issue on a fresh install of Monokrom from a deb package.

**Comment by TurBoss** [comment]
same issue here looks it has to be with vcpchooser

**Comment by kang2k10** [comment]
Sorry, i'm mixed QtVcp & QtPyVcp

**Comment by antarcticstar1** [comment]
How to solve this problem？

**Comment by joco-nz** [comment]
Due to the changes in how Debian 12 and other recent distros treat non Debian packaged python use:

https://www.qtpyvcp.com/install/apt_install.html

Unless you are trying to do a developer install. In which case look at the relevant pages on the same site.
