### ISSUE TITLE
Display Info and Error Notifications

### ISSUE THREAD

**Issue by Gnevko** [kcjengr/qtpyvcp#27]
Hi 

If I have a little bit more errors or infos let say as usual, than I can see only first(old) notifications in the list and the new notifications will not be displayed at all (see screen shot).

<img width="1242" alt="notofocations problem" src="https://user-images.githubusercontent.com/35346815/69482471-17d61280-0e1c-11ea-893d-a3e3cde09858.png">

**Comment by TurBoss** [comment]
I reversed the notifications order
thanks

**Comment by Gnevko** [comment]
gut idea! but i think additionally will be better to display only new notifications, let say, received in last 5 minutes.

**Comment by TurBoss** [comment]
not time but count looks better to me
so only show the latest 5 messages or something like that

**Comment by Gnevko** [comment]
agree :)

**Comment by TurBoss** [comment]
this was fixed on master will be out soon

Thanks for report

**Comment by TurBoss** [comment]
this is fixed on 0.3.7
thanks
