### ISSUE TITLE
Not run after installation

### ISSUE THREAD

**Issue by inghvar** [kcjengr/qtpyvcp#29]
I have installed qtpyvcp on Debian 9 as it's describe in docs "Quick Start". Installation go without errors. When I run LCNC after this I get error:
![image](https://user-images.githubusercontent.com/2820486/71426624-63c5e280-267a-11ea-895f-aef8a014af4a.png)

**Comment by TurBoss** [comment]
Hello,

what version of linuxcnc are you using?

 2.7 does not work whith qtpyvcp you need 2.8 and up


Thanks for using QtpyVCP

**Comment by inghvar** [comment]
Yes, I have upgraded linuxcnc and all work well
Thanks

**Comment by TurBoss** [comment]
you are wellcome
