### ISSUE TITLE
MDIButton - regex failing when adding negative sign in front of parameter

### ISSUE THREAD

**Issue by joco-nz** [kcjengr/qtpyvcp#30]
https://github.com/kcjengr/qtpyvcp/blob/7b0afb48405e39b517fc88fd80a3c4486fb8674a/qtpyvcp/widgets/button_widgets/mdi_button.py#L16

Using a command string of this style:  G10L20P0X-#<manualXYoffset>
causes the regex to return an empty result.  The '-' breaks the recognition pattern.

A regex pattern like:
`PARSE_VARS = re.compile(r'([a-zA-Z0-9_-]*)#<([^>]+)>', re.I)`
produces the correct result.  The `*` might be able to be replaced with `+`. The key is the group matching on the desired character ranges and the two specifics inside the `[]` with the `*` or `+` being used for a "greedy" match.

I have applied this fix to my local repo and it delivers the desired behaviour.

This simple code in a python interactive interpreter can prove the mechanic:
```
import re
cmd = "G10L20P0X-#<manualXYoffset>"
PARSE_VARS = re.compile(r'([a-zA-Z0-9_-]*)#<([^>]+)>', re.I)
vars = PARSE_VARS.findall(cmd)
```

Cheers.

**Comment by KurtJacobson** [comment]
@joco-nz thanks for the very nice bug report, and fix!
The regex was broken in other ways too, it only matched the last variable. Yours works correctly, and is much more efficient (20 steps vs. 110).
