### ISSUE TITLE
Wrong preview of rounded rectangle path in probe-basic.

### ISSUE THREAD

**Issue by rmu75** [kcjengr/qtpyvcp#42]
I'm not sure if this is the proper place to report that, I think this is not really a problem of probe basic, but a problem in the vtk backplot.

Description of problem is here https://github.com/LinuxCNC/linuxcnc/issues/892

**Comment by TurBoss** [comment]
Hello, 

I took the file Jepler uploaded and it runs fine on a metric sim

![Captura de pantalla de 2020-06-30 16-44-13](https://user-images.githubusercontent.com/184088/86140377-162aa680-baf1-11ea-8b24-e02a7fe19343.png)

**Comment by TurBoss** [comment]
G92 is not a well tested feature

**Comment by rmu75** [comment]
> I took the file Jepler uploaded and it runs fine on a metric sim

I have no doubt that the file displays and works fine under normal circumstances. Can you check what happens with G92 offset(s)?

**Comment by TurBoss** [comment]
sure will take a look tonight

**Comment by TurBoss** [comment]
Hello, I just created a branch called "VTK_G92" in https://github.com/kcjengr/qtpyvcp
it should fix load files with a G92 set

**Comment by TurBoss** [comment]
hello, 
did you have the opportunity test the fix?

Thanks

**Comment by rmu75** [comment]
Sorry for the late reply. Just tested it, and it seems to work.

**Comment by TurBoss** [comment]
no problem 
thanks for testing

i have to investigate this in deep because I don't like the way i did
it messes with having multiple parts in g5x and didn't expend much more time on that 

i have other branch wich went worse...

so the thing is on the air

**Comment by TurBoss** [comment]
thanks to @85vmh this issue is fixed now

I'm closing this issue

thank you
