### ISSUE TITLE
Errors behind main GUI with Mate window manager

### ISSUE THREAD

**Issue by sttts** [kcjengr/qtpyvcp#51]
The error popups show up behind the qtpyvcp main (fullscreen) window, i.e. invisible in normal operations.

Debian 10 Buster with Mate and marco window manager.

**Comment by TurBoss** [comment]
Hello,

the fullscreen mode has some issues with the notification popups they can't go more levels up than the full screen

**Comment by TurBoss** [comment]
Hello, 

sorry for the late reply
this may be fixed in #56 

Thanks for the report

**Comment by sttts** [comment]
Doesn't look it is fixed.

Talking about these notifications:

<img width="530" alt="Bildschirmfoto 2020-10-27 um 22 40 18" src="https://user-images.githubusercontent.com/730123/97365114-70702400-18a5-11eb-88ed-519054b9b658.png">

**Comment by sttts** [comment]
These are linuxcnc widgets, aren't they? I.e. not Qt and hence with a different parent window.

**Comment by TurBoss** [comment]
Thanks!
I managed to fix the notifications :partying_face: 

thoose fixes are on latest master


>These are linuxcnc widgets, aren't they? I.e. not Qt and hence with a different parent window.

The native notifications which come configured on ProbeBasic are made with QWtidgets
There is a option in custom_comfig.yml that allows you to switch to DBus based notifications but doesn't work on all systems

https://github.com/kcjengr/probe_basic/blob/master/config/probe_basic/custom_config.yml
something like...
```yaml

data_plugins:
  notifications:
    provider: qtpyvcp.plugins.notifications:Notifications
    kwargs:
      enabled: True
      mode: native | dbus

```
and again thanks for the feddback!

**Comment by sttts** [comment]
With dbus I now get visible notifications. Unfortunately, only one. If there are two or more notifications only the last one is visible.

**Comment by TurBoss** [comment]
trigger notifications by hand does the same... only the latest is shown

```
$ notify-send "Title" "Message"

**Comment by sttts** [comment]
Compare https://github.com/kcjengr/qtpyvcp/tree/Notifictions. There @TurBoss prototyped setting the notification widget's parent to the main window. This works for me with Mate window manager.

**Comment by TurBoss** [comment]
I only need to ask @KurtJacobson if this is the correct place to init post main window

https://github.com/kcjengr/qtpyvcp/compare/Notifictions#diff-94fc3bc6e7fc8a770ba01b4c3b7d5117a29f10243fb0eb988bf0b4ebee3bcdd2R254

**Comment by TurBoss** [comment]
done thanks for the feedback
