### ISSUE TITLE
DOC / BUG / Dependency

### ISSUE THREAD

**Issue by robertspark** [kcjengr/qtpyvcp#86]
rob@RobsCNC:~/qtpyvcp/docs$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v4.1.2
[qtpyvcp][INFO]  Logging to /home/rob/qtpyvcp.log (logger.py:97)

Extension error:
Could not import extension notfound.extension (exception: No module named 'notfound')
make: *** [Makefile:53: html] Error 2

Note: Docs in Probe Basic (doc_src) built fine before attempting to run make html in qtpyvcp/docs
___________________________________________________________________________________

Fixed following running + builds fine:

`pip install sphinx-notfound-page`

**Comment by TurBoss** [comment]
Thanks I added that package to the python3 branch I hope it will be released soon

Thanks
